version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: crypto_bot
      POSTGRES_USER: crypto_user
      POSTGRES_PASSWORD: your_password_here
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  bot:
    build: .
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DATABASE_URL: postgresql://crypto_user:your_password_here@postgres:5432/crypto_bot
      ADMIN_IDS: ${ADMIN_IDS}
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs

volumes:
  postgres_data: